apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
              ## kubectl create secret genric secret_name --from-literal key=value
              ## genric is a type of secret which indicates that we are saving some key value pairs together
              ## from literal indicates that we are going to add the secret information into this command not in file
              ## a secret is an object like pods and deplyoments we create it using the imperative approach
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  # this name is the secret_name specified in the command of storing secret
                  name: pgpassword
                  # key is the key we specified in the secret
                  key: PGPASSWORD
